name: BlockyRain
main: com.blockycraft.blockyrain.BlockyRain
version: 1.0
author: Bernardo Zukerman
description: Plugin de votação para parar ou continuar a chuva no servidor.
api-version: 1.7.3
commands:
  sim:
    description: Vota para parar a chuva.
    usage: /sim
  nao:
    description: Vota para continuar a chuva.
    usage: /nao
permissions:
  blockyrain.vote:
    description: Permite votar para parar ou continuar a chuva.
    default: true
